"""add cf user to user

Revision ID: 08eee033848e
Revises: 3f657ead958d
Create Date: 2021-08-12 17:05:33.199407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08eee033848e'
down_revision = '3f657ead958d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeforces_userinfo', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'codeforces_userinfo', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codeforces_userinfo', type_='foreignkey')
    op.drop_column('codeforces_userinfo', 'user_id')
    # ### end Alembic commands ###
