"""add username and password field

Revision ID: 26c438e9c293
Revises: d29266dacf2e
Create Date: 2021-08-12 15:52:54.645061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c438e9c293'
down_revision = 'd29266dacf2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
